import { Manrope, Source_Code_Pro, Oswald } from "next/font/google";
import "../globals.css";
import StickyContactBar from "@/components/shared/StickyContactBar";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div
      className={`${manrope.variable} ${sourceCodePro.variable} ${oswald.variable} antialiased`}
    >
      <StickyContactBar />
      {children}
    </div>
  );
}
