import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "../globals.css";
import StickyContactBar from "@/components/shared/StickyContactBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} antialiased`}
    >
      <StickyContactBar />
      {children}
    </div>
  );
}
